title: "Mark Porter"
description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam"
about: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam"
location: "Waterloo, Canada"
email: markporter4321@gmail.com
baseurl: ""
url: "http://markzporter.me" # replace by your site's url
linkedin_username: markzporter
github_username:  ladyashburnham

# google analytics tracking code, please change the value
g_analytics: "UA-85020443-1"

# language settings
isolang: en
close_btn: "Close"
home_btn: "Home"
projects_btn: "Projects"
posts_btn: "Posts"
imprint_btn: "Imprint"
name_badge: "an article by"
rss_badge: "Subscribe feed!"

# build settings
markdown: kramdown

# exclude files
exclude:
  - LICENSE
  - README.md