title: "Mark Porter"
description: "I am a Computer Science Co-op student at the University of Waterloo."
about: "This is a website designed to serve as my personal site to show work that I've done."
location: "Waterloo, Canada"
email: markporter4321@gmail.com
baseurl: ""
url: "http://markzporter.me" # replace by your site's url
linkedin_username: markzporter
github_username:  ladyashburnham

# google analytics tracking code, please change the value
g_analytics: "UA-85020443-1"

# language settings
isolang: en
close_btn: "Close"
home_btn: "Home"
projects_btn: "Projects"
posts_btn: "Posts"
imprint_btn: "Imprint"
name_badge: "an article by"
rss_badge: ""

# build settings
markdown: kramdown

# exclude files
exclude:
  - LICENSE
  - README.md
